name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Compile and run each .c file
      run: |
        for file in První\ ročník/Jazyky/C/*.c; do
          echo "Compiling $file"
          gcc "$file" -o "${file%.c}.out"
          
          if [ $? -eq 0 ]; then
            echo "Running ${file%.c}.out"

            # Run the executable and redirect stdin from /dev/null to simulate empty input
            ./"${file%.c}.out" < /dev/null
            
            # Capture the exit code
            exit_code=$?
            
            if [ $exit_code -ne 0 ]; then
              echo "Skipped ${file%.c}.out due to possible user input or error."
            else
              echo "${file%.c}.out completed successfully."
            fi
          else
            echo "Compilation failed for $file"
            exit 1
          fi
        done
