name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      run: sudo apt-get install python3

    - name: Check All Python Files in Subdirectories
      run: |
        find . -name "*.py" | while read -r file; do
          python3 -m py_compile "$file"
          if [ $? -eq 0 ]; then
            echo "Syntax check successful for $file"
          else
            echo "Syntax check failed for $file"
            exit 1
          fi
        done

    - name: Verify All Compiled Files Exist
      run: |
        find . -name "*.py" | while read -r file; do
          compiled_file="${file}c"
          if [ -f "$compiled_file" ]; then
            echo "Compiled file $compiled_file exists."
          else
            echo "Compiled file $compiled_file does not exist."
            exit 1
          fi
        done

    - name: Output Success Message
      run: echo "All Python files were checked successfully."
